### ISSUE TITLE
Use same translation logic for different entities

### ISSUE THREAD

**Issue by szakhlypa** [edgehog-device-manager/edgehog#255]
Align/share translation logic:

`Edgehog.BaseImages.update_base_image(base_image, %{"description" => %{"en-US" => ""}})` returns `{:ok, base_image}`

`Edgehog.Devices.update_system_model(system_model, %{"description" => %{"en-US" => ""}})` raises `BadMapError` exception

**Comment by rbino** [comment]
Translation logic was revamped during Ash porting so we can consider this closed
