### ISSUE TITLE
Add 'housekeeping' API to create and delete tenants

### ISSUE THREAD

**Issue by davidebriani** [edgehog-device-manager/edgehog#290]
A set of APIs should be made available to perform the following operations:
- Create an Edgehog tenant.
  - It should be possible to specify the private key for the tenant.
  - It should be possible to specify a reference to an Astarte realm and its private key.
- Delete an Edgehog tenant.

It's safe to assume that the associated Astarte realm will be created and deleted out-of-band.

The APIs can have an interface separated from the existing GraphQL schema, e.g. REST APIs.

**Comment by rbino** [comment]
We should also define how this API will be authenticated
