### ISSUE TITLE
Remove get/list reads and just use the default read

### ISSUE THREAD

**Issue by rbino** [edgehog-device-manager/edgehog#522]
This is something we initially did to have different descriptions for the two queries, but now the description can be passed [inline](https://hexdocs.pm/ash_graphql/dsl-ashgraphql-resource.html#graphql-queries-get-description), and `get? true` doesn't really have any effect on GraphQL, so we should just use the default read for both.

Note that the default read paginates by default, so we have to pass paginate_with: nil to the list query until we handle pagination project-wide.

```elixir
queries do
  get :resource, :read do
    description "blabla"
  end
  
  list :resources, :read do
    description "blablab"
    paginate_with nil
  end
end

# ...
actions do
  defaults [:read]
end
```

**Comment by davidebriani** [comment]
Closing as fixed by #550
