### ISSUE TITLE
Reconcile Container interfaces

### ISSUE THREAD

**Issue by rbino** [edgehog-device-manager/edgehog#610]
Once finalized, add the [new interfaces](https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/pull/64) to [this directory](https://github.com/edgehog-device-manager/edgehog/tree/main/backend/priv/astarte_resources/interfaces) so they get added to realms that use Edgehog.

**Comment by noaccOS** [comment]
the interfaces have been gradually added to the repository. as of now, the final version of the interfaces have all been included in the feature branch
