### ISSUE TITLE
Add container_management capability

### ISSUE THREAD

**Issue by rbino** [edgehog-device-manager/edgehog#615]
Add it to the list of capabilities [here](https://github.com/edgehog-device-manager/edgehog/blob/main/backend/lib/edgehog/devices/device/types/capability.ex) and add it [here](https://github.com/edgehog-device-manager/edgehog/blob/1cd7df0671e9ad40c0bf17c4fb5316ad96e497b0/backend/lib/edgehog/capabilities.ex#L35) with the list of interfaces needed to support it (i.e. the new Astarte interfaces)

**Comment by noaccOS** [comment]
implemented in #659
