### ISSUE TITLE
containers: add support for interface "io.edgehog.devicemanager.apps.CreateDeploymentRequest"

### ISSUE THREAD

**Issue by lusergit** [edgehog-device-manager/edgehog#626]
ref: #614 
interface [here](https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/pull/64/files#diff-0dca9ed7fcb1bfebebedef0923960992343e05b57c1b3da4e812fa1978f9b375)

**Comment by noaccOS** [comment]
closed by #652
