### ISSUE TITLE
 containers: add support for interface "io.edgehog.devicemanager.apps.CreateVolumeRequest"

### ISSUE THREAD

**Issue by lusergit** [edgehog-device-manager/edgehog#627]
ref: #614 
interface [here](https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/pull/64/files#diff-6bac58c5fef03499b5c438fb668d6f44817fa36d391cb7878f95b5b31f86e631)

**Comment by noaccOS** [comment]
closed by #693
