### ISSUE TITLE
containers: add support for interface "io.edgehog.devicemanager.apps.CreateImageRequest"

### ISSUE THREAD

**Issue by lusergit** [edgehog-device-manager/edgehog#630]
ref: #614 
interface [here](https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/pull/64/files#diff-33bbcd4723777662206f11b5f0f24a6d22ef942a1e72c198279c73531e5cf6a6)

**Comment by noaccOS** [comment]
closed by #640
