### ISSUE TITLE
containers: Add `Containers.Container` resource

### ISSUE THREAD

**Issue by lusergit** [edgehog-device-manager/edgehog#644]
Attributes

- `id` (uuid primary key)
- `restart_policy` (enum with possible values `:nil`, `:no`, `:always`, `:unless_stopped` and `:on_failure`)
- `hostname` (string)
- `env` (map)
- `privileged` (boolean)

fields come from the [`io.edgehog.devicemanager.apps.CreateContainerRequest` interface](https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/blob/055d6266c4f0b7612dd5838f71b062ba49999641/io.edgehog.devicemanager.apps.CreateContainerRequest.json)

**Comment by noaccOS** [comment]
closed by #645
