### ISSUE TITLE
containers: Deployment status

### ISSUE THREAD

**Issue by lusergit** [edgehog-device-manager/edgehog#675]
the `deployment` resource should handle a status update from the astarte interface, i.e., [L102-L120 in `handle_trigger.ex`](https://github.com/edgehog-device-manager/edgehog/blob/3f273bef883b5b957c7f1ef9def591879bf39af3/backend/lib/edgehog/triggers/handler/manual_actions/handle_trigger.ex#L107-L120) should update a property in `deployment.ex`

**Comment by noaccOS** [comment]
implemented in #676
