### ISSUE TITLE
Refreshing the application deployments with a refetchable GraphQL fragment doesn't work

### ISSUE THREAD

**Issue by davidebriani** [edgehog-device-manager/edgehog#735]
In the Deployed Applications tab of the Device page, when the user clicks on the Deploy/Start/Stop buttons, a corresponding GraphQL mutation is run to deploy/start/stop the deployment.
After the mutation succeeds, the frontend tries to re-fetch the GraphQL fragment about deployedApplications.

Using a Relay refetchable fragment for the deployedApplications is a good approach when working with Relay..
However Relay uses the `node` query instead of the initial `device` query when refetching the fragment, and the `node` query doesn't currently support fetching relationships on the node resource (applicationDeployments of the device): see also https://github.com/ash-project/ash_graphql/issues/99

When the `node` query returns without deployments, all deployments previously visible disappear from the UI.
The user has to refresh the page (which uses the `device` GraphQL query) to correctly fetch the existing deployments and see them again.

**Comment by noaccOS** [comment]
fixed in #736
