### ISSUE TITLE
Support for external devices when using docker compose

### ISSUE THREAD

**Issue by sorru94** [edgehog-device-manager/edgehog#758]
When following Edgehog in 5 minutes, Edgehog is set up using Docker Compose.
With this method, connecting devices simulated on the same host machine running the Edgehog instance is possible.
However, some Edgehog devices are intended to run on external hardware.
This should be supported by the Docker compose setup to facilitate first-time users in trying out Edgehog.

**Comment by davidebriani** [comment]
Closing as addressed by #759
